### ISSUE TITLE
Add option to compact CSV and keep delimeter

### ISSUE THREAD

**Issue by dmonder** [dakaraphi/vscode-extension-transformer#11]
This extension would be great if you could do align csv and unalign csv. This would allow me to see the data in columns and even do some edits and then put everything back together.

Also, why do you remove the comma when doing the align? That breaks the csv.

**Comment by dakaraphi** [comment]
Thanks, will add this in next update.

**Comment by dakaraphi** [comment]
Changed behavior to keep delimeter so that data can be used for round trip editing.
Added new command to compact the aligned CSV
https://github.com/dakaraphi/vscode-extension-transformer/commit/73ac95fc7f86964080488df6b650fec70c92d84d

**Comment by dakaraphi** [comment]
@dmonder published an update with this change.  Let me know if this works ok for you.

**Comment by dmonder** [comment]
Works great. Thank you for your quick response. This is very helpful.
