### ISSUE TITLE
how to undo earlier line selection

### ISSUE THREAD

**Issue by williamvm** [dakaraphi/vscode-extension-transformer#12]
escape does not undo

**Comment by dakaraphi** [comment]
@williamvm could you describe a little more detail about your scenario?
What command are you executing and what you expect to happen when you undo?

**Comment by williamvm** [comment]
I work with log files. open a single file. filter lines say on a url. the file shrinks from 6000 to 20 lines, great. now I want filter lines say on errormsg on the full original 6000 lines. how to get back without opening the original file.

**Comment by dakaraphi** [comment]
@williamvm If you are using `Transform: filter lines...` then this modifies the document in the current editor.  You should be able to just `undo` in the editor.  Such as `ctrl + z`

If you are using `Transform: filter lines as new document...`, then the original should still be open in the left side editor, and the modified version is in the 2nd editor column.  In this case, I would just execute the command again with focus on the original document in the left column, which would then update the modified version being displayed with the new filter you set.
