### ISSUE TITLE
Documentation: Filter Lines As New Document/Parent levels

### ISSUE THREAD

**Issue by balazser** [dakaraphi/vscode-extension-transformer#32]
Could you write some additional lines of documentation to explain the 
`Filter Lines As New Document/ Parent levels` command, because I still do not understand it. Seems does nothing for me. If I use it with the positive number then it gives back the whole text and with negative do some changes.
What would be the section level?
Thank you!

**Comment by dakaraphi** [comment]
@balazser The `level` here is related to the indentation level.  Similar to vscode folding levels.  A `section` here is essentially what would be folded if you were to fold a line.

Examples:
- `0` will include all siblings of the matched lines.  Where a sibling is determined by being at the same indentation level next to the matched line.
- `1` will include all siblings + the parent siblings ( one less indentation level )
