### ISSUE TITLE
Align CSV doesn't respect text delimiter

### ISSUE THREAD

**Issue by jeremysimmons** [dakaraphi/vscode-extension-transformer#34]
When values contain a text delimiter like ", with a separator character inside like , then the text delimiter is not considered, and the delimiter inside is used.

https://github.com/dakaraphi/vscode-extension-transformer#align-csv

Input
```
Company Name,Address 1
"fill,buz","foo,bar"
```

Actual Output
```
Company Name ,Address 1 
"fill        ,buz"      
```

Expected Output
```
Company Name ,Address 1 
"fill,buz"   ,"foo,bar"
```

**Comment by dakaraphi** [comment]
@jeremysimmons Fixed in v1.8.0
