### ISSUE TITLE
How to invoke "Align CSV" 

### ISSUE THREAD

**Issue by mguttman** [dakaraphi/vscode-extension-transformer#35]
From the documentation it is not clear how to invoke the "Align CSV".
From the animated screenshot it is not clear where to click for the magic to happen.
I tried many left and right clicks on every imaginable and non-imaginable places but none duplicated the screenshot.
Please help....
Meir

**Comment by dakaraphi** [comment]
@mguttman Could you post a small example of CSV that does not work for you?
