### ISSUE TITLE
The align csv function does not support Chinese well

### ISSUE THREAD

**Issue by yangzhou04** [dakaraphi/vscode-extension-transformer#37]
Transformer is really a good extension. However, The align csv function does not support Chinese well. I hope you could fix this:

test-case:
```
this,中,some
is,国(备注),other
a,语（其他）,key
test,言,contents

```
then, choose "Transform Align CSV" and the result is:

```
this ,中     ,some     
is   ,国(备注) ,other    
a    ,语（其他） ,key      
test ,言     ,contents 
```

**Comment by dakaraphi** [comment]
Unfortunately this is not possible.  VSCode doesn't expose API's that would allow gathering the font width of characters or placing them precisely.  I can only align by character count.
