### ISSUE TITLE
extension randomly stops working

### ISSUE THREAD

**Issue by ElSamhaa** [dakaraphi/vscode-extension-transformer#38]
I don't know if there is any log file that I can provide here.

**Comment by dakaraphi** [comment]
Is this a problem that just started?  Like after a vscode update?
When this happens, do all commands stop working? or just some commands?

**Comment by ElSamhaa** [comment]
actually I've just started using it today.
So I can't really associate it with latest update specifically. But vscode it on latest version.

**Comment by dakaraphi** [comment]
The Log (Extension host) might have something useful.
Also, look for any stacktraces being logged at the time it stops working.

**Comment by ElSamhaa** [comment]
I suspected that, but nothing is written there.
no errors notifications. just doesn't work as if nothing happened.
it might be worth mentioning that in sometimes when it works, `ctrl + z` won't revert action.

**Comment by dakaraphi** [comment]
There should be at least a line for when the extension is activated.  Something like...
`[2019-11-19 09:50:09.980] [exthost] [info] ExtensionService#_doActivateExtension dakara.transformer {"startup":false,"extensionId":{"value":"dakara.transformer","_lower":"dakara.transformer"},"activationEvent":"onCommand:dakara-transformer.uniqueLines"}
[2019-11-19 09:50:09.981] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/chadmeadows/.vscode/extensions/dakara.transformer-1.6.0/out/extension`

`ctrl + z` not working is also unusual.  The extension doesn't do anything in regards to undo events.  That is managed by vscode.

When it stops working, do other extensions continue working normally?  Do you have to restart vscode for it to start working again?

**Comment by ElSamhaa** [comment]
> When it stops working, do other extensions continue working normally? Do you have to restart vscode for it to start working again?

yes, I had to restart vscode for it to work again.
it might help to mention that among the runs, I've used it on remote hosts, with `remote ssh`.

is there any toggle that raises that level log of extensions to better track this when I reproduce the issue?

**Comment by dakaraphi** [comment]
There is no additional logging.  If an error occurs, it should already get logged with stacktrace.

I haven't used vscode with `remote ssh`.  It would be interesting if you see if the extension seems to work fine without it.  I'm not immediately sure in what way this would have an effect.

The only other suggestion I can think of is to try disabling all other extensions and see if the transformer extensions works fine by itself.

**Comment by dakaraphi** [comment]
Closing due to not enough info to determine issue
