### ISSUE TITLE
Feature request: Natural Sort Order

### ISSUE THREAD

**Issue by adamsmd** [dakaraphi/vscode-extension-transformer#40]
I would like to request a way to sort in [Natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order) (i.e., sort alphabetically but group multi-digit numbers).

My use case is when I have a column of numbers that I want to sort numerically.  For example a sort result might be the following:

```
foo 2  bar 2
foo 2  bar 11
foo 11 bar 2
foo 11 bar 11
```

In theory, a "Sort by number" instead of "Sort by natural order" could also satisfy my use case, but I think "Sort by natural order" is more general.

**Comment by dakaraphi** [comment]
Added to v1.8.0
