### ISSUE TITLE
Two more split commands

### ISSUE THREAD

**Issue by mat-m** [dakaraphi/vscode-extension-transformer#41]
Nice extension which works well for my purpose.

One feature which will save me even more time, is to SplitBeforeDelimiter or SplitAfterDelimiter. It means that the delimiter will stay at Begin or End of Line, respectively.
My example:

When I wrap a list on multiple lines, I want to keep the comma. I know I can add it back with a search& replace, but it will be better if it is not eaten at all.

First example, constants set to reformat:
--------------------------------

```{plenty_of_long, but_variable_in_length, name_for_a_useful_project}```
after **SplitAfterDelimiter(",")** would give
```
{plenty_of_long,
 but_variable_in_length,
 name_for_a_useful_project}
```

Second example, splitting an options list for readability will keep all the details:
--------------------------------

```-e one=two -e three=four -e do_it=again -v -t 30```
after **SplitBeforeDelimiter(" -")** would give

```
 -e one=two
 -e three=four
 -e do_it=again
 -v
 -t 30
```

Thanks for reading

**Comment by mat-m** [comment]
Hello,

I tried to prepare a pull-request, but got an error:

```
[22:15:10] Starting compilation in watch mode...

src/Transforms.ts:4:40 - error TS2307: Cannot find module 'vscode-extension-common' or its corresponding type declarations.

4 import {Lines,Modify,Region,View} from 'vscode-extension-common'
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
``` 

Is there a trick to set this up, or some hidden prerequisites ?

Thanks for your help

**Comment by dakaraphi** [comment]
@mat-m you will need the `vscode-extension-common` locally.  https://github.com/dakaraphi/vscode-extension-common

**Comment by mat-m** [comment]
@dakaraphi : I did it but I should miss something: 

Both source clones are here
```
➜ ll
total 20K
drwxrwxr-x  6 mm mm 4,0K sept. 19 22:17 vscode-extension-common
drwxrwxr-x  9 mm mm 4,0K sept. 19 22:25 vscode-extension-transformer
drwxrwxr-x 10 mm mm 4,0K avril 20 00:42 vscode-open-in-github
```

And **common** looks detected in **transformer**.

```
17:25:37 in vscode-extension-transformer on  master [!?] is 📦 v1.8.0 via ⬢ v10.13.0 
➜ find . -name "vscode-extension-common"
./out/vscode-extension-common
./vscode-extension-common
./node_modules/vscode-extension-common
```
The second one is a try to symlink the **common**'s clone into **transformer**'s, just in case.

When I try to debug, Compilation gives:
![image](https://user-images.githubusercontent.com/1039753/94368994-809ab500-00e7-11eb-9ef1-05c94c1d5b9d.png)

**Comment by dakaraphi** [comment]
@mat-m did you first try it with just `npm install`?  That actually should create the symlink.

**Comment by mat-m** [comment]
@dakaraphi Thanks. Since I saw some downlaods, I assumed `npm install` was triggered by the run. Seems not ;-)

**Comment by mat-m** [comment]
`npm install ` creates the link in 

```
lrwxrwxrwx 1 mm mm   29 sept. 27 23:56 vscode-extension-common -> ../../vscode-extension-common
drwxrwxr-x 4 mm mm 4,0K sept. 27 23:56 vscode-test
drwxrwxr-x 2 mm mm 4,0K sept. 27 23:56 wrappy

23:58:15 in vscode-extension-transformer/node_modules on  master 
```

I followed following steps: 
1. git clone common
2. code common
3. npm install in the terminal
4. git clone transformer
5. code transformer
6. npm install
7. F5

I managed to run the Comment-sample from https://github.com/microsoft/vscode-extension-samples successfully, using steps 4-7.
I am using node 14.

My wild guess is that I miss a command to build common, maybe ?

Thanks for your time.

**Comment by dakaraphi** [comment]
ok, when you do `F5` vscode is only going to compile that project.
So I think the missing step is compiling the `common` package.
So from the vscode terminal in the common package. Execute `npm run vscode:prepublish`

**Comment by mat-m** [comment]
That did it, thanks !

**Comment by dakaraphi** [comment]
@mat-m thanks for the pull request!  New version published.
