### ISSUE TITLE
Make line operations work on multi selections

### ISSUE THREAD

**Issue by JensRoland** [dakaraphi/vscode-extension-transformer#42]
I find that I use line transformations all the time, but I use multi-selection even more. I often want to transform a number of selected regions, but I always have to copy/paste or manipulate them into a set of lines, do the transform, and then return them to their original locatinos/structure.

If the simpler line operations (sort, reverse, randomize, and maybe trim) could be performed on multiselected regions instead of just lines, that would be a game changer for multiselection manipulation.

For example, consider reversing the order of the color codes in the following:

```python
plotLine1 = Line(
  color="green",
         -----                <---- selection
  legend="Revenues"
)
plotLine2 = Line(
  color="yellow",
         ------               <---- selection
  legend="Costs"
)
plotLine3 = Line(
  color="red",
         ---                  <---- selection
  legend="Profits"
)
```

Or sorting the city names alphabetically in the following (a little contrived since it could be done trivially in the code itself, but this could be a list in a text document or a non-contiguous selection):

```python
cities = ["Stockholm", "Copenhagen", "Oslo", "Helsinki", "Reykjavik", "Nuuk"]
           ---------    ----------    ----    --------    ---------    ----        <---- selections
```

**Comment by dakaraphi** [comment]
Thanks, that is a very interesting idea.

**Comment by dakaraphi** [comment]
@JensRoland I just released an update that now has 4 new commands that operate on selections.
Let me know how this works for you.

**Comment by JensRoland** [comment]
I just tried the new feature, it's amazing! Thank you so much -- this is the kind of operation that makes coworkers stop you in the middle of a pair programming or demo session to ask how the hell you did that. Love it!
