### ISSUE TITLE
ShiftRight and ShiftLeft (Feature)

### ISSUE THREAD

**Issue by JensRoland** [dakaraphi/vscode-extension-transformer#43]
With multiple lines (or multiselect regions) selected, the ShiftRight / ShiftLeft commands would 'rotate' the lines/selections. E.g. selecting the following lines:

```
Jerry Cobb
Laura Ortega
Owen Castillo
Randall Boone
```

then invoking ShiftRight once, would become:

```
Randall Boone
Jerry Cobb
Laura Ortega
Owen Castillo
```

**Comment by dakaraphi** [comment]
Implemented as rotate forward and rotate backward

**Comment by JensRoland** [comment]
This is so cool! Thank you so much, now I just need to figure out what shortcut keys to assign these.
