### ISSUE TITLE
Merge annsk.alignment

### ISSUE THREAD

**Issue by duckimann** [dakaraphi/vscode-extension-transformer#56]
I tried to merge [this extension](https://github.com/annsk/vscode-alignment) to Transformer but i can't. Can you do it pls?

**Comment by d-akara** [comment]
Why would you want to merge another extension when you can just install it separately?

**Comment by duckimann** [comment]
Well, I just want to keep the amount of extension i have to install to a minimum and less settings i have to find. Additionally, the "Align to Cursor" kinda broken.

![150822_09-32-18-PM_wCyVtvK4e7](https://user-images.githubusercontent.com/46382253/184655344-9e57ff4a-d534-49dc-9ff4-92ac218da905.gif)

**Comment by d-akara** [comment]
You can create your own extension pack to better help manage your own installs.  I did that for myself as an example - https://marketplace.visualstudio.com/items?itemName=dakara.dakara-editor-core-pack

The Align To Cursor aligns only text to the right side of the cursor to the position of the cursor where there is a gap of empty space.  It doesn't parse the text and try to figure out the syntactic character separators.
